name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch: # Add this line to allow manual trigger
    inputs:
      exampleInput: # Optional: You can define inputs for the workflow
        description: "Example input"
        required: false
        default: "default value"

env:
  FRONTEND_IMAGE_NAME: frontend
  SPENDING_IMAGE_NAME: spending
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t $DOCKER_USERNAME/$FRONTEND_IMAGE_NAME:latest -f ./frontend/Dockerfile ./frontend
          docker push $DOCKER_USERNAME/$FRONTEND_IMAGE_NAME:latest

      - name: Build and push spending Docker image
        run: |
          docker build -t $DOCKER_USERNAME/$SPENDING_IMAGE_NAME:latest -f ./services/spending/Dockerfile ./services/spending
          docker push $DOCKER_USERNAME/$SPENDING_IMAGE_NAME:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name finances-app-cluster-v2

      - name: Apply Kubernetes manifests
        run: kubectl apply -k infra/k8s/base
